"use strict";
const assert=require("node:assert/strict");
const {createContract,transition,renew,occupancyEffect,availabilityEffect}=require("./contract-lease");
const base=()=>createContract({contractId:"lease01",organizationId:"org01",tenantRef:"tenant_synthetic",unitRef:"yang01",rentAmountMinor:350000,currency:"mxn",billingSchedule:"monthly",startDate:"2026-10-01",endDate:"2027-03-31"});
let c=base();assert.equal(c.state,"draft");assert.equal(c.currency,"MXN");assert.equal(Object.isFrozen(c),true);
let x=transition(c,{to:"review",actorId:"agent01",eventId:"evt01",at:"2026-09-20T12:00:00-06:00"});c=x.contract;
x=transition(c,{to:"approved",actorId:"agent01",eventId:"evt02",at:"2026-09-21T12:00:00-06:00",authorizationRef:"auth01"});c=x.contract;
x=transition(c,{to:"active",actorId:"agent01",eventId:"evt03",at:"2026-10-01T00:00:00-06:00",authorizationRef:"auth02"});c=x.contract;
assert.equal(x.event.type,"property.contract.activated.v1");assert.equal(x.event.rentAmountMinor,350000);assert.equal(x.event.organizationId,"org01");
const r=renew(c,{newEndDate:"2027-09-30",actorId:"agent01",eventId:"evt04",at:"2027-03-01T10:00:00-06:00",authorizationRef:"auth03"});
assert.equal(r.event.type,"property.contract.renewed.v1");assert.equal(r.contract.endDate,"2027-09-30");
assert.throws(()=>renew(c,{newEndDate:"2027-03-31",actorId:"agent01",eventId:"evt05",at:"x",authorizationRef:"auth04"}),/INVALID_RENEWAL_TERM/);
assert.throws(()=>transition(base(),{to:"active",actorId:"agent01",eventId:"evt06",at:"x",authorizationRef:"auth05"}),/INVALID_CONTRACT_TRANSITION/);
assert.throws(()=>transition(c,{to:"terminated",actorId:"agent01",eventId:"evt07",at:"x"}),/INVALID_AUTHORIZATION_REF/);
const expired=transition(c,{to:"expired",actorId:"agent01",eventId:"evt08",at:"2027-04-01T00:00:00-06:00"});
assert.equal(expired.contract.state,"expired");assert.equal(occupancyEffect().automatic,false);assert.equal(availabilityEffect().automatic,false);
const terminated=transition(c,{to:"terminated",actorId:"agent01",eventId:"evt09",at:"2027-02-01T00:00:00-06:00",authorizationRef:"auth09"});
assert.equal(terminated.contract.state,"terminated");assert.equal(availabilityEffect().reason,"TURNOVER_VERIFICATION_REQUIRED");
assert.throws(()=>createContract({contractId:"lease_bad_date",organizationId:"org01",tenantRef:"tenant_synthetic",unitRef:"yang01",rentAmountMinor:350000,currency:"MXN",billingSchedule:"monthly",startDate:"2026-02-31",endDate:"2026-03-31"}),/INVALID_START_DATE/);\nassert.throws(()=>transition(c,{to:"terminated",actorId:"agent01",eventId:"evt_bad_at",at:"not-a-time",authorizationRef:"auth10"}),/INVALID_AT/);\nassert.throws(()=>createContract({contractId:"lease02",organizationId:"org01",tenantRef:"tenant_synthetic",unitRef:"yang01",rentAmountMinor:350000,currency:"MXN",billingSchedule:"monthly",startDate:"2027-04-01",endDate:"2027-03-01"}),/INVALID_TERM/);
console.log("PASS: Contract/Lease V0.1 lifecycle, authorization and no implicit occupancy/availability");
