"use strict";
const assert=require("node:assert/strict");
const {unit}=require("./property-model");
const {transition,appendEvent}=require("./property-events");
const base=unit({unitId:"yang01",buildingId:"adn10",propertyId:"adn001",number:"01",type:"suite"});
const metadata={actorId:"admin01",eventId:"evt01",at:"2026-10-03T18:00:00-06:00"};
const a=transition(base,{...metadata,to:"captured"});
assert.equal(a.record.verification,"captured");
assert.equal(base.verification,"draft");
assert.equal(a.event.from,"draft");
assert.throws(()=>transition(base,{...metadata,to:"active",evidenceId:"photo01"}),/INVALID_TRANSITION/);
const b=transition(a.record,{...metadata,eventId:"evt02",to:"verification"});
assert.throws(()=>transition(b.record,{...metadata,eventId:"evt03",to:"verified"}),/EVIDENCE_REQUIRED/);
const c=transition(b.record,{...metadata,eventId:"evt03",to:"verified",evidenceId:"photo01"});
const d=transition(c.record,{...metadata,eventId:"evt04",to:"active",evidenceId:"inspection01"});
assert.equal(d.record.verification,"active");
const events=appendEvent(appendEvent({},a.event),b.event);
assert.equal(Object.keys(appendEvent(events,a.event)).length,2);
assert.throws(()=>appendEvent(events,{...a.event,to:"verified"}),/EVENT_ID_CONFLICT/);
assert.equal(Object.isFrozen(a.event),true);
console.log("PASS: Property Core verification transitions, evidence gates, immutable idempotent events");
