"use strict";
const assert=require("node:assert/strict");
const {property,building,unit}=require("./property-model");
const {publicCatalog}=require("./public-catalog");
const p=property({propertyId:"LAB-CATALOG-P1",name:"Pilot"}),b=building({buildingId:"LAB-CATALOG-B1",propertyId:p.propertyId,name:"Building"});
const make=(id,overrides={})=>unit({unitId:id,propertyId:p.propertyId,buildingId:b.buildingId,number:id,type:"studio",verification:"active",occupancy:"vacant",operation:"available",...overrides});
const publication=id=>({unitId:id,revision:4,priceMXN:2800,evidenceIds:["PRIVATE-EVIDENCE-01"],requestId:"PRIVATE-REQUEST"});
const row=(record,revision=4)=>({property:p,building:b,entity:{record,revision,publication:publication(record.unitId),events:{"PRIVATE-EVENT":{actorId:"PRIVATE-ADMIN"}}}});
const result=publicCatalog([row(make("LAB-CATALOG-U1")),row(make("LAB-CATALOG-U2",{occupancy:"occupied"})),row(make("LAB-CATALOG-U3"),5),null]);
assert.equal(result.items.length,1);
assert.equal(result.rejected.length,3);
assert.deepEqual(Object.keys(result.items[0]).sort(),["currency","monthlyRentMXN","propertyGroupId","propertyName","unitId","unitNumber","unitType"].sort());
assert.equal(JSON.stringify(result).includes("PRIVATE"),false);
assert.equal(result.rejected[0].reason,"NOT_VACANT");
assert.equal(result.rejected[1].reason,"STALE_PUBLICATION");
assert.equal(result.rejected[2].reason,"NOT_PUBLISHED");
const duplicate=publicCatalog([row(make("LAB-CATALOG-U1")),row(make("LAB-CATALOG-U1"))]);
assert.equal(duplicate.items.length,1);
assert.equal(duplicate.rejected[0].reason,"DUPLICATE_UNIT");
const other=property({propertyId:"LAB-CATALOG-P2",name:"Other"});
const otherBuilding=building({buildingId:"LAB-CATALOG-B2",propertyId:other.propertyId,name:"Other building"});
const otherUnit=unit({unitId:"LAB-CATALOG-U1",propertyId:other.propertyId,buildingId:otherBuilding.buildingId,number:"1",type:"studio",verification:"active",occupancy:"vacant",operation:"available"});
const isolated=publicCatalog([row(make("LAB-CATALOG-U1")),{property:other,building:otherBuilding,entity:{record:otherUnit,revision:4,publication:publication(otherUnit.unitId)}}]);
assert.equal(isolated.items.length,2);
const malformed={...row(make("LAB-CATALOG-BAD"))};
malformed.entity={...malformed.entity,record:{...malformed.entity.record,number:null}};
const resilient=publicCatalog([malformed,row(make("LAB-CATALOG-GOOD"))]);
assert.equal(resilient.items.length,1);
assert.equal(resilient.items[0].unitId,"LAB-CATALOG-GOOD");
assert.equal(resilient.rejected[0].reason,"INVALID_CATALOG_ROW");
const valid=row(make("LAB-CATALOG-SAME"));
const invalid={...valid,entity:{...valid.entity,record:{...valid.entity.record,number:null}}};
const sequence=publicCatalog([valid,invalid,valid]);
assert.equal(sequence.items.length,1);
assert.deepEqual(sequence.rejected.map(x=>x.reason),["INVALID_CATALOG_ROW","DUPLICATE_UNIT"]);
const recovery=publicCatalog([invalid,valid]);
assert.equal(recovery.items.length,1);
assert.equal(recovery.rejected[0].reason,"INVALID_CATALOG_ROW");
assert.throws(()=>publicCatalog(null),/INVALID_CATALOG_INPUT/);
console.log("PASS: minimal public catalog exposes only current eligible units and no internal evidence/events");
