"use strict";
const assert=require("node:assert/strict");
const {createCase,validateAdapter}=require("./case-contract");
const common={tenantId:"TENANT-A",caseId:"CASE-001",personId:"PERSON-001",requestId:"REQ-001"};
const propertyAdapter={id:"property",validate:c=>({allowed:c.context.unitEligible===true,reason:c.context.unitEligible===true?"ELIGIBLE":"UNIT_NOT_ELIGIBLE"})};
const telecomAdapter={id:"telecom",validate:c=>({allowed:c.context.coverage===true,reason:c.context.coverage===true?"COVERED":"NO_COVERAGE"})};
const property=createCase({...common,caseType:"visit",adapterId:"property",context:{unitId:"ADN-YANG-01",unitEligible:true}});
const telecom=createCase({...common,caseId:"CASE-002",requestId:"REQ-002",caseType:"installation",adapterId:"telecom",context:{coverage:false,service:"internet"}});
assert.equal(validateAdapter(property,propertyAdapter).allowed,true);
assert.equal(validateAdapter(telecom,telecomAdapter).reason,"NO_COVERAGE");
assert.throws(()=>validateAdapter(property,telecomAdapter),/ADAPTER_MISMATCH/);
assert.equal(property.context.unitId,"ADN-YANG-01");
const source={nested:{coverage:true}};
const detached=createCase({...common,caseId:"CASE-003",context:source,adapterId:"telecom",caseType:"installation"});
source.nested.coverage=false;
assert.equal(detached.context.nested.coverage,true);
assert.equal(Object.isFrozen(detached.context.nested),true);
assert.throws(()=>createCase({...common,tenantId:"../other",caseType:"visit",adapterId:"property"}),/INVALID_TENANTID/);
assert.throws(()=>createCase({...common,caseType:"visit",adapterId:"property",context:[]}),/INVALID_CONTEXT/);
console.log("PASS: shared case envelope supports property and telecom without sector-specific core fields");
